CREATE TABLE IF NOT EXISTS tokens (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    role VARCHAR(10) NOT NULL DEFAULT 'USER',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NULL
);

ALTER TABLE IF EXISTS tokens ADD COLUMN IF NOT EXISTS role VARCHAR(10) NOT NULL DEFAULT 'USER';

CREATE TABLE IF NOT EXISTS images (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    filename VARCHAR(500) NOT NULL,
    oss_key VARCHAR(500) NOT NULL UNIQUE,
    oss_url VARCHAR(2000) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL,
    md5_hash VARCHAR(32) NULL,
    width INT NULL,
    height INT NULL,
    token_id BIGINT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE IF EXISTS images ADD COLUMN IF NOT EXISTS md5_hash VARCHAR(32) NULL;
ALTER TABLE IF EXISTS images ADD COLUMN IF NOT EXISTS token_id BIGINT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_images_md5_hash ON images(md5_hash);