CREATE TABLE IF NOT EXISTS tokens (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    role VARCHAR(10) NOT NULL DEFAULT 'USER',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NULL
);

ALTER TABLE IF EXISTS tokens ADD COLUMN IF NOT EXISTS role VARCHAR(10) NOT NULL DEFAULT 'USER';
ALTER TABLE IF EXISTS tokens ADD COLUMN IF NOT EXISTS email VARCHAR(255) NULL;

CREATE TABLE IF NOT EXISTS images (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    filename VARCHAR(500) NOT NULL,
    oss_key VARCHAR(500) NOT NULL UNIQUE,
    oss_url VARCHAR(2000) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL,
    md5_hash VARCHAR(32) NULL,
    width INT NULL,
    height INT NULL,
    token_id BIGINT NULL,
    is_published BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE IF EXISTS images ADD COLUMN IF NOT EXISTS md5_hash VARCHAR(32) NULL;
ALTER TABLE IF EXISTS images ADD COLUMN IF NOT EXISTS token_id BIGINT NULL;
ALTER TABLE IF EXISTS images ADD COLUMN IF NOT EXISTS is_published BOOLEAN NOT NULL DEFAULT FALSE;
CREATE UNIQUE INDEX IF NOT EXISTS idx_images_md5_hash ON images(md5_hash);

CREATE TABLE IF NOT EXISTS app_settings (
    id BIGINT NOT NULL DEFAULT 1,
    upload_size_limit_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    upload_size_limit_mb INT NOT NULL DEFAULT 50,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
);

MERGE INTO app_settings (id, upload_size_limit_enabled, upload_size_limit_mb, updated_at)
    KEY(id) VALUES (1, FALSE, 50, CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS email_verification (
    email VARCHAR(255) PRIMARY KEY,
    code VARCHAR(10) NOT NULL,
    token_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS email_attempt_log (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    token_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS email_domains (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    domain VARCHAR(100) NOT NULL UNIQUE
);

MERGE INTO email_domains (id, domain) KEY(id) VALUES (1, 'qq.com');
MERGE INTO email_domains (id, domain) KEY(id) VALUES (2, 'outlook.com');
MERGE INTO email_domains (id, domain) KEY(id) VALUES (3, '163.com');

CREATE TABLE IF NOT EXISTS sessions (
    session_id VARCHAR(64) PRIMARY KEY,
    token_id BIGINT NOT NULL,
    role VARCHAR(10) NOT NULL DEFAULT 'USER',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (token_id) REFERENCES tokens(id)
);